export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGNUP_FAILED: 'LOGIN_SUCCESS',
  GET_STORIES_SUCCESS: 'GET_STORIES_SUCCESS',
  GET_STORIES_FAILURE: 'GET_STORIES_FAILURE',
  CREATE_STORY_SUCCESS: 'CREATE_STORY_SUCCESS',
  CREATE_STORY_FAILURE: 'CREATE_STORY_FAILURE',
};
